### ISSUE TITLE
[1.12.2] Conflict with Buildcraft Lib resulting in crash on launch

### ISSUE THREAD

**Issue by Raptor22a** [TwistedGate/ImmersivePetroleum#78]
### Description of the issue
Aside from the title, there's not much else that I can say, since I can't even get to the title screen; it crashes at the end of the forge load sequence, before the title screen pops up. I'd love to try Immersive Petroleum, but I also don't want to give up BuildCraft either.

### Versions and Modlist
**Immersive Engineering v0.12-98**
**Immersive Petroleum v1.12.2-1.1.9**
**Forge Version 1.12.2-14.23.5.2860**

### Crash Log
https://pastebin.com/mknEwyG3

**Comment by TwistedGate** [comment]
Support for 1.12.2 has been dropped since august last year (2021)

**Comment by masonbesmer** [comment]
> ### Description of the issue
> Aside from the title, there's not much else that I can say, since I can't even get to the title screen; it crashes at the end of the forge load sequence, before the title screen pops up. I'd love to try Immersive Petroleum, but I also don't want to give up BuildCraft either.
> 
> ### Versions and Modlist
> **Immersive Engineering v0.12-98** **Immersive Petroleum v1.12.2-1.1.9** **Forge Version 1.12.2-14.23.5.2860**
> 
> ### Crash Log
> https://pastebin.com/mknEwyG3

Did you ever find a fix for this? I'm having the same issue.

**Comment by brisingraerowing** [comment]
From reading the log and looking at the code, it seems that this is an issue with the Immersive Intelligence Packer multiblock.

**Comment by Raptor22a** [comment]
Is there anything that I can do about this, or am I out of luck?

**Comment by TwistedGate** [comment]
If they fix their machine, sure.. otherwise no

**Comment by Xeladin** [comment]
So does the error: {(java.lang.Error: Failed to create a page link for immersivepetroleum:schematic class flaxbeard.immersivepetroleum.common.items.ItemProjector ({ForgeCaps:{"astralsorcery:cap_item_amulet_holder":{}},id:"immersivepetroleum:schematic",Count:1b,tag:{multiblock:"II:Packer"},Damage:0s})
	at buildcraft.lib.client.guide.entry.PageEntryItemStack.iterateAllDefault(PageEntryItemStack.java:114)}
Have a solution or no? Because I'm having the same exact issue, did anyone found out what to do? For what I know, when I removed build craft the game started and played perfectly, but I would really like to have build craft in my mods

**Comment by brisingraerowing** [comment]
@Xeladin https://github.com/Pabilo8/ImmersiveIntelligence/issues/144#issuecomment-1051285353
