### ISSUE TITLE
[Suggestion] Let Coker Output Items to Adjacent Inventories

### ISSUE THREAD

**Issue by tukib** [TwistedGate/ImmersivePetroleum#82]
Unless I'm doing something wrong, currently the coker only outputs items (e.g. petcoke for sulf. diesel recipe) by dropping them below the chamber chutes.

I would expect the items to be inserted inside a barrel/chest/other inventory if placed directly under the chamber chutes. This would allow other methods of transporting items without creating item entities.

![example](https://o.lol-sa.me/8zmS5vJ.png)

**Comment by brisingraerowing** [comment]
You're supposed to use belts there to transport the items out.

**Comment by tukib** [comment]
> You're supposed to use belts there to transport the items out.

I know, this is a suggestion to also allow direct transfer

**Comment by voidsong-dragonfly** [comment]
The only reason the belts were not _built into the model of the coker_ was because it was an annoying technical challenge. **Use belts.**

**Comment by tukib** [comment]
Guys I know belts or other methods of moving item entities are required currently, lol. I claim that it is unnecessary to strictly require 1 extra block for automation as it serves no additional challenge and doesn't create any more sense of realism. Adding some compatibility with inventories will make the mod play nicer with other mods and won't break existing builds.

**Comment by voidsong-dragonfly** [comment]
Yes, and we're saying it's _entirely indented_ for them to be THE method of transfer. Use them, do it manually, or let the items rot.

**Comment by TwistedGate** [comment]
Im not going to do this, simply for the fact that i decided against it from the very early stages while developing the Coker. (Just it)

> I claim that it is unnecessary to strictly require 1 extra block for automation as it serves no additional challenge

Only in the context of using other mods does it feel or seem unnecessary.
As IP is an addon for *Immersive Engineering* and not mod *X*, it just happens to mostly have compabilites with other mods.
The coker is the only exception out of all other IE and IP machines that for once does *not* insert the output items into an inventory directly.

> doesn't create any more sense of realism

As if it is realistic to smack a pipe below the output chutes, which somehow is able to transfer all sorts of things. =P (Using some magical voodoo)

**Comment by ghost** [comment]
I really love the strict NO from the devs <3
As for the "belts are not part of the model because to difficult" - well, I'm sure it somehow can be done - but the way it is: able to place the belts on your own inside the in-world model - to me it's more of a feature then something missing due to technical diffiulties: it allows for free placement and routing - in a combine model I guess there would only two ways: the regular one to one side and a mirrored one to the other - which in turn would be more limitation then the "build your own"-way.
Please keep it this way!

Also: I know you guys working on it already - any rough estimate when 1.18 may could become available?

**Comment by TwistedGate** [comment]
Nice to see someone who gets it!

Nope, i don't do ETAs nor do i bother to even think about it.
Because it forces me to rush things and make low-ass quality and/or cobbled together crap.
(There is more to the port than meets the eye)

**Comment by ghost** [comment]
Ok, fair point - I guess a "when it's done" just fits it better than "planed for last week but delayed to next one". Unfortunately there're a couple of nice IE-addons which just came to live rather unfinished and got stuck in limbo. Although I have experience with Java for about 15 years - the most sophisticated project I actually finished was a two-player networked battle ships game. Sure I may could get myself into minecraft modding - but this would take time I currently don't really have (long work shifts and a few other projects already taking much of my free time).
I noticed quite some major changes over the last couple versions since 1.12 - so I guess both Minecraft itself as well as the forge modding has changed quite a lot with it - some maybe for good - but some certainly for worse. I can just imagine it requires quite some rewrite to update.
Anyway - keep it up - it's a nice add-on to one really nice mod. Would love to see more mods go this multi-block in-world models - but I'm also quite used to IC2 and BC5+ single-block machines - or thermal, although I never really played with it.
